title = "Electrolink config"

[server]
ip = "localhost"
port = 1883
keepalive = 60 # maximum period in seconds allowed between communications with the broker.

[thing]
# This name will be used to declare subscriptions
# for example if name is "weio" than topics will be :
# weio/command, weio/reply, weio/error
targetName = "weioESP" 
